services:
  - type: web
    name: inhutani-land
    env: php
    region: singapore
    plan: free
    buildCommand: |
      composer install --optimize-autoloader --no-dev
      php artisan key:generate --force
      php artisan storage:link
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:dummykeyplaceholderthatwillbeoverridden
      - key: APP_NAME
        value: "Inhutani Land Management"
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: sqlite
      - key: MAIL_MAILER
        value: log
